### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by btandersen383** [Goblenus/WallhavenApi#11]
Could you add a license to your repository? I think your code is great and would like to use it as part of a project of my own. I want to make sure you are properly credited for the work.

**Comment by Goblenus** [comment]
I have know a little about licence and how to choose right one, can you help me?

**Comment by btandersen383** [comment]
Sure thing, although I am still learning a lot myself. 

In general, your code is only *viewable* under the Github terms of service. Just putting the code out there does not make it truly open source. You need to add a license that will define the legal permissions to use/modify/distribute (or not) the code by others. To add a license to the repository, you simple create a file called LICENSE and copy in the full license you decide to use. Additionally, you can place an abbreviated version or reference to the license at the top of each source document, though depending on the project this may be overkill.

As for what license to choose, you have a lot of options. You can check out [ChooseALicense](https://choosealicense.com/) for a great guide. I will talk about the two I have seen and used:

The most permissive is the [MIT License](https://opensource.org/licenses/MIT) which basically allows anyone to do anything so long as the original license is attached. It is also very simple so it is a good place to start. 
The most common that I have seen is the [GNU General Public License](https://www.gnu.org/licenses/quick-guide-gplv3.html) of which there are a couple versions. This is noticeably more complex so I will not try to explain it here. It does apply more restrictive conditions for using the code but that shouldn't be an issue in this case. Either one would work easily on this project.

**Comment by Goblenus** [comment]
Just added MIT :)
