### ISSUE TITLE
Wallhaven is releasing an official API and doing breaking changes

### ISSUE THREAD

**Issue by MLutt** [Goblenus/WallhavenApi#2]
See https://alpha.wallhaven.cc/forums/thread/1778 - The complete API would have to be adjusted or made an interface to the new one to remain functional.

**Comment by Goblenus** [comment]
Thanks for notice. I wrote to https://alpha.wallhaven.cc/user/AksumkA to get access to API.

**Comment by MLutt** [comment]
Wallhaven alpha has ended, please mark the library as obsolete as it's non-functional from this point onwards....

**Comment by Goblenus** [comment]
You can use original_api_v1 branch to interact with new api. I going to merge it to master.

**Comment by Goblenus** [comment]
@MLutt merged to master
